// lab3 + 5/src/app/components/student-block/student-block.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Student } from '../../models/student.model';

@Component({
  selector: 'app-student-block',
  templateUrl: './student-block.component.html',
  styleUrls: ['./student-block.component.css']
})
export class StudentBlockComponent {
  @Input() student!: Student;
  @Output() edit = new EventEmitter<void>();
  @Output() delete = new EventEmitter<number>();

  onEdit() {
    this.edit.emit();
  }
  onDelete() {
    if (this.student.id) this.delete.emit(this.student.id);
  }
}

<div class="student">
  <div class="student-info">
    <div><strong>Ім'я:</strong> {{ student.firstName }}</div>
    <div><strong>Прізвище:</strong> {{ student.lastName }}</div>
    <div><strong>Дата народження:</strong> {{ student.birthDate }}</div>
    <div><strong>Група:</strong> {{ student.groupNumber }}</div>
  </div>
  <div class="student-actions">
    <button (click)="onEdit()">Редагувати</button>
    <button (click)="onDelete()">Видалити</button>
  </div>
</div>

// lab4/src/components/StudentBlock.jsx
export default function StudentBlock(
  {firstName, lastName, birthDate, groupNumber, onEdit, onDelete}) {
  return (
    <div className="student">
      <div className="student-info">
        <div><strong>Ім'я:</strong> {firstName}</div>
        <div><strong>Прізвище:</strong> {lastName}</div>
        <div><strong>Дата народження:</strong> {birthDate}</div>
        <div><strong>Група:</strong> {groupNumber}</div>
      </div>
      <div className="student-actions">
        <button title="Редагувати" onClick={onEdit}>✎</button>
        <button title="Видалити" onClick={onDelete}>🗑</button>
      </div>
    </div>
  );
}
